### ISSUE TITLE
Shall we make a release.

### ISSUE THREAD

**Issue by wushan** [IvanWei/passport-line-auth#14]
Shall we make a release contains newly features since last release is about half years ago.

**Comment by IvanWei** [comment]
@wushan Yesterday I notice that is not finish. In the past, this repository just remove options and etc, didn't have big trouble. Then [v0.2.4](https://github.com/IvanWei/passport-line-auth/releases/tag/v0.2.4) is fine, v0.2.5 will release today.

**Comment by IvanWei** [comment]
[v0.2.5](https://www.npmjs.com/package/passport-line-auth) is release and published. This issue will be closed.

**Comment by wushan** [comment]
awsome.
