### ISSUE TITLE
On v0.2.5. Line server returns "'state' is not specified" error.

### ISSUE THREAD

**Issue by sside** [IvanWei/passport-line-auth#16]
## Specifications
- Node version: 10.15.0
- Platform:
  - [ ] Windows
  - [x] macOS
  - [ ] Linux

## Expected Behavior
When use this strategy, redirect to Line login url.

## Actual Behavior
When I updated to v0.2.5 from v0.2.4, Line server redirects callback url with error message "'state' is not specified." 

## Steps to Reproduce the Problem
```
passport.use(new LineStrategy( {
        channelID: my_line_channel,
        channelSecret: my_line_secret,
        callbackURL: `${ "myserverurl" }/callback/line`,
        passReqToCallback: true,
        scope: [
            "profile",
            "openid"
        ],
        botPrompt: "aggressive", 
    } )
```
and
`passport.authenticate( "line" )`

**Comment by IvanWei** [comment]
@sside I found this bug that what happened when [PR 13](https://github.com/IvanWei/passport-line-auth/commit/6c07ae77c180b759d1ff874155c066b1f2626af9) remove `option.state`. I will fix this weekend.

**Comment by IvanWei** [comment]
Hi @sside I fix it, please update version from v0.2.5 to [v0.2.6](https://github.com/IvanWei/passport-line-auth/pull/17).

This issue will be closed.

**Comment by IvanWei** [comment]
@wushan state is back with option on v0.2.6. v0.2.5 had been deprecated.

**Comment by sside** [comment]
@IvanWei 
Very thank you for fix quickly. I'll try it.
