### ISSUE TITLE
Upgrading to LINE Login v2.1

### ISSUE THREAD

**Issue by boybundit** [IvanWei/passport-line-auth#3]
LINE Login has introduced `v2.1` which supports the OpenID Connect protocol and allows you to retrieve user information with ID tokens. Is there any plan for this package to upgrade from `v2` to `v2.1`?

https://developers.line.me/en/docs/line-login/web/integrate-line-login/

**Comment by IvanWei** [comment]
This package upgrades to v2.1 this month.

**Comment by IvanWei** [comment]
@boybundit This is done, so I close this issue.

[v0.1.0](https://github.com/IvanWei/passport-line-auth/releases/tag/v0.1.0)
